/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProductReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "product";
};

export type Order = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products?: Array<{
    product?: ProductReference;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
    };
    _key: string;
  }>;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "stripe" | "paypal";
  status?: "pending" | "paid" | "shipped" | "delivered" | "cancelled";
  orderDate?: string;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: string;
  brand?: string;
  sku?: string;
  gender?: string;
  nickname?: string;
  releaseDate?: string;
  variants?: Array<{
    color?: string;
    size?: string;
    variantSku?: string;
    stock?: number;
    price?: number;
    variantImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "variant";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  status?: "new" | "hot" | "sale";
  productType?: "tshirt" | "jacket" | "pants" | "hoodie" | "short" | "others";
  osType?: string;
  operatingSystemsSupported?: string;
  versionType?: string;
  productStatus?: string;
  placeOfOrigin?: string;
  brandName?: string;
  activation?: string;
  shippingMethod?: string;
  packageInclude?: string;
  language?: string;
  warranty?: string;
  deliveryTime?: string;
  support?: string;
  function?: string;
  paymentMethods?: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProductReference
  | Order
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: app/(client)/api/order/route.ts
// Variable: GET_ORDER_BY_NUMBER_QUERY
// Query: *[_type == 'order' && orderNumber == $orderNumber][0]{      ...,products[]{        ...,product->      }    }
export type GET_ORDER_BY_NUMBER_QUERY_RESULT = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      description?: string;
      brand?: string;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "paypal" | "stripe";
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
} | null;

// Source: sanity/helpers/queries.ts
// Variable: PRODUCT_BY_SLUG_QUERY
// Query: *[_type == 'product' && slug.current == $slug] | order(name asc) [0]
export type PRODUCT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  intro?: string;
  description?: string;
  brand?: string;
  sku?: string;
  gender?: string;
  nickname?: string;
  releaseDate?: string;
  variants?: Array<{
    color?: string;
    size?: string;
    variantSku?: string;
    stock?: number;
    price?: number;
    variantImage?: {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    };
    _type: "variant";
    _key: string;
  }>;
  price?: number;
  discount?: number;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  stock?: number;
  status?: "hot" | "new" | "sale";
  productType?: "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
  osType?: string;
  operatingSystemsSupported?: string;
  versionType?: string;
  productStatus?: string;
  placeOfOrigin?: string;
  brandName?: string;
  activation?: string;
  shippingMethod?: string;
  packageInclude?: string;
  language?: string;
  warranty?: string;
  deliveryTime?: string;
  support?: string;
  function?: string;
  paymentMethods?: string;
} | null;

// Source: sanity/helpers/queries.ts
// Variable: CATEGORIES_QUERY
// Query: *[_type=="category"] | order(title asc)
export type CATEGORIES_QUERY_RESULT = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
}>;

// Source: sanity/helpers/queries.ts
// Variable: MY_ORDERS_QUERY
// Query: *[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){    ...,    paymentMethod,    receiptUrl,    products[]{      ...,product->    }  }
export type MY_ORDERS_QUERY_RESULT = Array<{
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl: string | null;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      description?: string;
      brand?: string;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod: "paypal" | "stripe" | null;
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
}>;

// Source: sanity/helpers/queries.ts
// Variable: ORDER_BY_NUMBER_QUERY
// Query: *[_type == 'order' && orderNumber == $orderNumber][0]{    ...,products[]{      ...,product->    }  }
export type ORDER_BY_NUMBER_QUERY_RESULT = {
  _id: string;
  _type: "order";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  orderNumber?: string;
  invoice?: {
    id?: string;
    number?: string;
    hosted_invoice_url?: string;
  };
  receiptUrl?: string;
  stripeCheckoutSessionId?: string;
  stripeCustomerId?: string;
  clerkUserId?: string;
  customerName?: string;
  email?: string;
  stripePaymentIntentId?: string;
  products: Array<{
    product: {
      _id: string;
      _type: "product";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      name?: string;
      slug?: Slug;
      images?: Array<{
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }>;
      intro?: string;
      description?: string;
      brand?: string;
      sku?: string;
      gender?: string;
      nickname?: string;
      releaseDate?: string;
      variants?: Array<{
        color?: string;
        size?: string;
        variantSku?: string;
        stock?: number;
        price?: number;
        variantImage?: {
          asset?: SanityImageAssetReference;
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
        };
        _type: "variant";
        _key: string;
      }>;
      price?: number;
      discount?: number;
      categories?: Array<
        {
          _key: string;
        } & CategoryReference
      >;
      stock?: number;
      status?: "hot" | "new" | "sale";
      productType?:
        "hoodie" | "jacket" | "others" | "pants" | "short" | "tshirt";
      osType?: string;
      operatingSystemsSupported?: string;
      versionType?: string;
      productStatus?: string;
      placeOfOrigin?: string;
      brandName?: string;
      activation?: string;
      shippingMethod?: string;
      packageInclude?: string;
      language?: string;
      warranty?: string;
      deliveryTime?: string;
      support?: string;
      function?: string;
      paymentMethods?: string;
    } | null;
    quantity?: number;
    selectedVariant?: {
      color?: string;
      size?: string;
      variantSku?: string;
      price?: number;
    };
    _key: string;
  }> | null;
  totalPrice?: number;
  currency?: string;
  amountDiscount?: number;
  paymentMethod?: "paypal" | "stripe";
  status?: "cancelled" | "delivered" | "paid" | "pending" | "shipped";
  orderDate?: string;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == 'order' && orderNumber == $orderNumber][0]{\n      ...,products[]{\n        ...,product->\n      }\n    }": GET_ORDER_BY_NUMBER_QUERY_RESULT;
    "*[_type == 'product' && slug.current == $slug] | order(name asc) [0]": PRODUCT_BY_SLUG_QUERY_RESULT;
    '*[_type=="category"] | order(title asc)': CATEGORIES_QUERY_RESULT;
    "*[_type == 'order' && clerkUserId == $userId] | order(orderDate desc){\n    ...,\n    paymentMethod,\n    receiptUrl,\n    products[]{\n      ...,product->\n    }\n  }": MY_ORDERS_QUERY_RESULT;
    "*[_type == 'order' && orderNumber == $orderNumber][0]{\n    ...,products[]{\n      ...,product->\n    }\n  }": ORDER_BY_NUMBER_QUERY_RESULT;
  }
}
